### ISSUE TITLE
希望大佬可以建个QQ群

### ISSUE THREAD

**Issue by jhyscode** [WZMIAOMIAO/deep-learning-for-image-processing#246]
希望大佬可以建个QQ群，方便大家交流一下，大佬没空管理的话，可以交由其他人管理也行。谢谢！

**Comment by zmz125** [comment]
同意同意（￣︶￣）↗

**Comment by macqueen09** [comment]
我作为粉丝迷弟先带头创建个专属群吧，群有模有样了之后再邀请WZ大佬吧


QQ群
657562630

**Comment by macqueen09** [comment]
![image](https://user-images.githubusercontent.com/16522286/121171063-98d2ee80-c888-11eb-8799-535fe5fd4ee1.png)

**Comment by macqueen09** [comment]
ding

**Comment by Dd-ouni** [comment]
> 我作为粉丝迷弟先带头创建个专属群吧，群有模有样了之后再邀请WZ大佬吧
> 
> QQ群
> 657562630

找不到这个QQ群

**Comment by Zlj-github** [comment]
> 我作为粉丝迷弟先带头创建个专属群吧，群有模有样了之后再邀请WZ大佬吧
> 
> QQ群 657562630

这哪个顽皮的孩子设置的群验证问题，pascal voc数据集多少类？除了4个大类，20个小类，1个背景，这几个数字可还有别的答案？

**Comment by macqueen09** [comment]
搜不到。我还在看设置哪儿出了问题。但是扫码的话是可以进的。目前群里一共138人，其中114人在线

**Comment by RooKichenn** [comment]
大佬你好，我是从b站过来的；我想修改一下ResNet50+FPN的网络，在里面添加一些模块，但是没有对应的预训练权重，可以上传一下ResNet50+FPN的训练的代码吗

**Comment by Zlj-github** [comment]
> 大佬你好，我是从b站过来的；我想修改一下ResNet50+FPN的网络，在里面添加一些模块，但是没有对应的预训练权重，可以上传一下ResNet50+FPN的训练的代码吗

兄弟，直接用Dectron2的库改一下就成，方便滴很

**Comment by RooKichenn** [comment]
哈哈哈，我刚入门两个月的小白，这个库我也没用过，刚上网搜了一下，准备学一下这个库；我就是前一阵子在b站看完你的Faster RCNN，然后又看了注意力机制模块，想加到这个ResNet50+FPN网络里面，但是网上说网络结构越深这个注意力机制越鸡肋，但是我还是想加进去试试；这个Dectron2是可以直接训练模型权重吗，还是说可以直接给出新加入模块的权重呀；非常感谢大哥！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.******@***.***&gt;; 
发送时间: 2021年12月9日(星期四) 下午4:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] 希望大佬可以建个QQ群 (#246)





  
大佬你好，我是从b站过来的；我想修改一下ResNet50+FPN的网络，在里面添加一些模块，但是没有对应的预训练权重，可以上传一下ResNet50+FPN的训练的代码吗
  
兄弟，直接用Dectron2的库改一下就成，方便滴很
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by eureka-haha** [comment]
> 657562630

搜不到哎
