### ISSUE TITLE
为了得到你的许可

### ISSUE THREAD

**Issue by Saya520r** [WZMIAOMIAO/deep-learning-for-image-processing#348]
非常抱歉打扰您，由于不知道您的联系方式，只能以这样的方式来征得您的同意。我写的论文里用了您的SSD和Faster rcnn代码做实验，我将在我的代码里公开我的代码与我的实验数据。代码链接会放您的。非常感谢您的代码以及视频讲解，帮助我很多。希望你能同意。谢谢你（哔哩哔哩也有私信过您）。如果您同意的话，请记得回复我一下。再次感谢您。

**Comment by lzh1998-lzh** [comment]
您好，您是不是搞错了？哪个代码？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月6日(星期一) 中午11:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 
非常抱歉打扰您，由于不知道您的联系方式，只能以这样的方式来征得您的同意。我写的论文里用了您的SSD和Faster rcnn代码做实验，我将在我的代码里公开我的代码与我的实验数据。代码链接会放您的。非常感谢您的代码以及视频讲解，帮助我很多。希望你能同意。谢谢你（哔哩哔哩也有私信过您）。如果您同意的话，请记得回复我一下。再次感谢您。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Saya520r** [comment]
霹雳啪啦呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jansen ***@***.***&gt;
发送时间: 2021年9月6日 12:03
收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&gt;
抄送: 冉烁依 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)

**Comment by Saya520r** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jansen ***@***.***&gt;
发送时间: 2021年9月6日 12:03
收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&gt;
抄送: 冉烁依 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)

**Comment by lzh1998-lzh** [comment]
我b站没发过视频，。。你是不是搞错了，你怎么知道我邮箱的呢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月6日(星期一) 中午12:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 霹雳啪啦呀 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: jansen ***@***.***&amp;gt; 
 发送时间: 2021年9月6日 12:03 
 收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&amp;gt; 
 抄送: 冉烁依 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348) 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Saya520r** [comment]
那你是噼里啪啦吗。博主名字。 &nbsp; 我在GitHub上联系的，发的issues，也许你绑定了邮箱吧，所以你邮箱直接收到了。我并不知道你的邮箱。是自动发送的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jansen ***@***.***&gt;
发送时间: 2021年9月6日 12:06
收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&gt;
抄送: 冉烁依 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 我b站没发过视频，。。你是不是搞错了，你怎么知道我邮箱的呢 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年9月6日(星期一) 中午12:04 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348) 
 
 
 
 
 
  霹雳啪啦呀  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: jansen ***@***.***&amp;amp;gt;  
  发送时间: 2021年9月6日 12:03  
  收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&amp;amp;gt;  
  抄送: 冉烁依 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  
  主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Saya520r** [comment]
你看。github地址

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jansen ***@***.***&gt;
发送时间: 2021年9月6日 12:06
收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&gt;
抄送: 冉烁依 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 我b站没发过视频，。。你是不是搞错了，你怎么知道我邮箱的呢 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年9月6日(星期一) 中午12:04 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348) 
 
 
 
 
 
  霹雳啪啦呀  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: jansen ***@***.***&amp;amp;gt;  
  发送时间: 2021年9月6日 12:03  
  收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&amp;amp;gt;  
  抄送: 冉烁依 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  
  主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Saya520r** [comment]
我用的这个人的代码。请问是你吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jansen ***@***.***&gt;
发送时间: 2021年9月6日 12:06
收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&gt;
抄送: 冉烁依 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 我b站没发过视频，。。你是不是搞错了，你怎么知道我邮箱的呢 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年9月6日(星期一) 中午12:04 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348) 
 
 
 
 
 
  霹雳啪啦呀  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: jansen ***@***.***&amp;amp;gt;  
  发送时间: 2021年9月6日 12:03  
  收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&amp;amp;gt;  
  抄送: 冉烁依 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  
  主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WZMIAOMIAO** [comment]
你好，可以的，但我建议最好还是标注官方的源码链接，比如Faster RCNN的源码是Pytorch官方提供的，SSD的代码是NVIDIA官方提供的，我视频里都有讲过具体的来源。

**Comment by lzh1998-lzh** [comment]
您好，请问您是谁，您说的是哪个视频？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月6日(星期一) 中午12:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 
你好，可以的，但我建议最好还是标注官方的源码链接，比如Faster RCNN的源码是Pytorch官方提供的，SSD的代码是NVIDIA官方提供的，我视频里都有讲过具体的来源。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Saya520r** [comment]
好的，非常感谢您。但是我确实就是用的您的代码。所以就放您的，就好了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WuZhe ***@***.***&gt;
发送时间: 2021年9月6日 12:22
收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&gt;
抄送: 冉烁依 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 
你好，可以的，但我建议最好还是标注官方的源码链接，比如Faster RCNN的源码是Pytorch官方提供的，SSD的代码是NVIDIA官方提供的，我视频里都有讲过具体的来源。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Saya520r** [comment]
非常抱歉啊 博主已经回复我了。我就是在GitHub上联系的。我不知道为什么你和博主都会收到信息。今可以看一下GitHub，https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/issues/348



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jansen ***@***.***&gt;
发送时间: 2021年9月6日 12:26
收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&gt;
抄送: 冉烁依 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 您好，请问您是谁，您说的是哪个视频？ 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年9月6日(星期一) 中午12:22 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348) 
 
 
 
 
 
   
 你好，可以的，但我建议最好还是标注官方的源码链接，比如Faster RCNN的源码是Pytorch官方提供的，SSD的代码是NVIDIA官方提供的，我视频里都有讲过具体的来源。 
   
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WZMIAOMIAO** [comment]
@lzh1998-lzh 不好意思，不知道为什么github会发邮件给你，我现在关闭这个issue，应该不会在收到邮件了。

**Comment by lzh1998-lzh** [comment]
我不是噼里啪啦，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月6日(星期一) 中午12:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 那你是噼里啪啦吗。博主名字。 &amp;nbsp; 我在GitHub上联系的，发的issues，也许你绑定了邮箱吧，所以你邮箱直接收到了。我并不知道你的邮箱。是自动发送的 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: jansen ***@***.***&amp;gt; 
 发送时间: 2021年9月6日 12:06 
 收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&amp;gt; 
 抄送: 冉烁依 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348) 
 
 
 
 
 
  我b站没发过视频，。。你是不是搞错了，你怎么知道我邮箱的呢  
   
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年9月6日(星期一) 中午12:04  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)  
   
   
   
   
   
   霹雳啪啦呀   
     
     
     
   发自我的iPhone   
     
     
   ------------------ 原始邮件 ------------------   
   发件人: jansen ***@***.***&amp;amp;amp;gt;   
   发送时间: 2021年9月6日 12:03   
   收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&amp;amp;amp;gt;   
   抄送: 冉烁依 ***@***.***&amp;amp;amp;gt;, Author ***@***.***&amp;amp;amp;gt;   
   主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)   
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Saya520r** [comment]
对不起 我联系上了。我搞错了 非常抱歉打扰您





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jansen ***@***.***&gt;
发送时间: 2021年9月6日 12:06
收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&gt;
抄送: 冉烁依 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 我b站没发过视频，。。你是不是搞错了，你怎么知道我邮箱的呢 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年9月6日(星期一) 中午12:04 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348) 
 
 
 
 
 
  霹雳啪啦呀  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: jansen ***@***.***&amp;amp;gt;  
  发送时间: 2021年9月6日 12:03  
  收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&amp;amp;gt;  
  抄送: 冉烁依 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  
  主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lzh1998-lzh** [comment]
你能把网址发给我看看吗？我真的晕了
+




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月6日(星期一) 中午12:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348)





 好的，非常感谢您。但是我确实就是用的您的代码。所以就放您的，就好了。 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: WuZhe ***@***.***&amp;gt; 
 发送时间: 2021年9月6日 12:22 
 收件人: WZMIAOMIAO/deep-learning-for-image-processing ***@***.***&amp;gt; 
 抄送: 冉烁依 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 主题: 回复：[WZMIAOMIAO/deep-learning-for-image-processing] 为了得到你的许可 (#348) 
 
 
 
 
 
   
 你好，可以的，但我建议最好还是标注官方的源码链接，比如Faster RCNN的源码是Pytorch官方提供的，SSD的代码是NVIDIA官方提供的，我视频里都有讲过具体的来源。 
   
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
